name: deploy
on:
  push:
    branches: [ development ]
  workflow_dispatch:
   inputs:
    bump-mode:
      description: 'Bump mode'
      required: true
      default: 'none'
      type: choice
      options:
        - major
        - minor
        - patch

jobs:

  checkout:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      
  bump-Version:
   runs-on: ubuntu-latest
   needs: checkout
   steps:
    - name: Bump Version
      uses: msnijder30/maven-version-bump-action@v5
      with:
          github-token: ${{ secrets.github_token }}
          bump-mode: ${{ github.event.inputs.bump-mode }}
