name: deploy
on:
  push:
    branches: [ development ]
  workflow_dispatch:
   inputs:
    bump-mode:
      description: 'Bump mode'
      required: true
      default: 'none'
      type: choice
      options:
        - major
        - minor
        - patch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bump Version
        id: bump
        uses: msnijder30/maven-version-bump-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          bump-mode: ${{ github.event.inputs.bump-mode }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: maven-settings-action
        uses: s4u/maven-settings-action@v2.5.0
        
      - run: mvn clean verify compile package site:site javadoc:javadoc javadoc:jar -f pom.xml
